import { Column } from 'typeorm';

export function HideAutoGeneratedId() {
    return function (target: any, propertyName: string) {
        Column('int', { name: '_id', select: false })(target, propertyName);
    };
}